# .github/coderabbit.yml

review:
    enable: true
    language: ["ts", "js", "html", "css"]
    model: gpt-4
    prompt: |
        请以中文进行代码审查，风格保持专业简洁，重点关注以下几点：
        1. 是否存在潜在的逻辑错误或代码缺陷
        2. 是否违反前端开发最佳实践
        3. 是否有更简洁、清晰的写法
        4. 是否具有良好的可维护性和可读性
        5. 代码风格是否统一，是否符合项目规范
        如果一切正常，也请简要说明“代码质量良好”。

auto_comment:
    enable: true

auto_approve:
    enable: true
